CREATE TABLE IF NOT EXISTS motos (
    id BIGSERIAL PRIMARY KEY,
    modelo VARCHAR(255) NOT NULL,
    placa VARCHAR(8) NOT NULL UNIQUE,
    status VARCHAR(20) DEFAULT 'DISPONIVEL',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observacoes TEXT
);
